[package]
authors = ["Yuri Iozzelli <y.iozzelli@gmail.com>"]
name = "telegram-bot"
version = "0.1.0"

[dependencies]
error-chain = "0.10.0"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
hyper = "0.11"
hyper-tls = "0.1"
telegram-bot-types = "0.1.1"
